apiVersion: v1
kind: Namespace
metadata:
  name: soc-platform
  labels:
    environment: production
    app.kubernetes.io/name: soc-platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
