export interface YARAOrSigmaDetection {
  id: string;
  engine: 'YARA' | 'SIGMA';
  ruleName: string;
  severity: string;
  matchedTarget: string;
  mitreTechnique: string;
  summary: string;
}

export function parseYaraSigmaResults(rawContent: string): YARAOrSigmaDetection[] {
  const detections: YARAOrSigmaDetection[] = [];
  const lines = rawContent.split('\n').filter(l => l.trim().length > 0);

  lines.forEach((line, idx) => {
    if (line.includes('rule:') || line.includes('YARA') || line.includes('SIGMA') || line.match(/^[a-zA-Z0-9_]+\s+\/path\//)) {
      const isYara = line.includes('YARA') || line.match(/^[a-zA-Z0-9_]+\s+\/path\//);
      const parts = line.split(/\s+/);
      const ruleName = parts[0] || 'SUSPICIOUS_RULE_MATCH';
      const target = parts[1] || 'File / Telemetry Stream';

      detections.push({
        id: `DETECTION-${idx + 1}`,
        engine: isYara ? 'YARA' : 'SIGMA',
        ruleName,
        severity: ruleName.toLowerCase().includes('critical') || ruleName.toLowerCase().includes('mimikatz') ? 'Critical' : 'High',
        matchedTarget: target,
        mitreTechnique: isYara ? 'T1027 (Obfuscated Files or Information)' : 'T1059.001 (PowerShell Execution)',
        summary: `Rule match generated by ${isYara ? 'YARA Binary Engine' : 'Sigma Log Rule Processor'}: ${line}`
      });
    }
  });


  return detections;
}
